Repository invesalius/invesalius3, pull requests merged in 2023-08, with the labels that each got.

#617 ADD: Tooltips for Viewer Volume (bottom right) tool bar
  invesalius/gui/default_viewers.py
Labels: ui/ux

#649 Markers saved after creating marker using 'Create marker'-message
  invesalius/gui/task_navigator.py
Labels: bug

#655 FIX: Applies fiducial marker saving in state fiee to new navigation UI
  invesalius/gui/task_navigator.py
Labels: bug

#653 Export 3D surfaces in world space
  invesalius/data/slice_.py
  invesalius/data/surface.py
  invesalius/data/viewer_volume.py
  invesalius/gui/data_notebook.py
  invesalius/gui/dialogs.py
  invesalius/gui/task_exporter.py
Labels: enhancement, new feature

#659 Replace FileDialogCustomizeHook uses with another dialog type
  invesalius/constants.py
  invesalius/gui/dialogs.py
  invesalius/gui/task_exporter.py
  invesalius/gui/task_navigator.py
Labels: bug, enhancement, ui/ux
