Repository invesalius/invesalius3, pull requests merged in 2023-07, with the labels that each got.

#530 Added one more message to stop crashes when opening a project while n…
  invesalius/control.py
Labels: bug, neuronavigation

#606 Dialog with cancel option for exit
  invesalius/gui/frame.py
  invesalius/session.py
Labels: enhancement

#615 Object registration refactor
  invesalius/gui/task_navigator.py
  invesalius/navigation/navigation.py
Labels: neuronavigation

#625 Improve showing/hiding the slices' cross intersection tool
  invesalius/data/styles.py
  invesalius/data/styles_3d.py
  invesalius/data/viewer_slice.py
  invesalius/data/viewer_volume.py
  invesalius/gui/frame.py
  invesalius/gui/task_navigator.py
Labels: bug, enhancement, neuronavigation, ui/ux
