Repository invesalius/invesalius3, pull requests merged in 2024-05, with the labels that each got.

#761 ADD: Sorting functionality to the marker list in GUI
  invesalius/data/markers/marker.py
  invesalius/gui/task_navigator.py
  invesalius/navigation/markers.py
Labels: new feature, ui/ux

#755 FIX: Fix syntax of developer examples inside the docs.
  docs/devel/example_closure.py
  docs/devel/example_pubsub.py
  docs/devel/example_singleton.py
  docs/devel/example_singleton_pubsub.py
Labels: bug, document

#765 FIX: Error in MacOS for ID 0 in right click of Markers Menu Item
  invesalius/gui/task_navigator.py
Labels: bug

#763 Bugfixes and features
  invesalius/constants.py
  invesalius/data/actor_factory.py
  invesalius/data/coordinates.py
  invesalius/data/coregistration.py
  invesalius/data/markers/marker.py
  invesalius/data/markers/marker_transformator.py
  invesalius/data/markers/surface_geometry.py
  invesalius/data/styles.py
  invesalius/data/styles_3d.py
  invesalius/data/tracker_connection.py
  invesalius/data/viewer_volume.py
  invesalius/data/visualization/coil_visualizer.py
  invesalius/data/visualization/marker_visualizer.py
  invesalius/gui/dialogs.py
  invesalius/gui/preferences.py
  invesalius/gui/task_navigator.py
  invesalius/gui/task_tractography.py
  invesalius/navigation/markers.py
  invesalius/navigation/navigation.py
  invesalius/navigation/robot.py
  invesalius/navigation/tracker.py
  navigation/objects/aim_with_zero_angle_highlighted.stl
Labels: bug, enhancement, new feature, neuronavigation
