Repository invesalius/invesalius3, pull requests merged in 2024-06, with the labels that each got.

#779 FIX: Change project after loading fMRI overlay
  invesalius/data/slice_.py
Labels: bug

#781 FIX: Height of markers list was occluding robot buttons
  invesalius/gui/task_navigator.py
Labels: bug, neuronavigation, ui/ux

#792 FIX: Fail to import NIfTI with multiple volumes
  invesalius/data/imagedata_utils.py
  invesalius/gui/dialogs.py
  invesalius/reader/others_reader.py
Labels: bug, enhancement

#799 FIX: Refine called non-existing UpdateGUI
  invesalius/gui/task_navigator.py
Labels: bug, ui/ux
