Repository invesalius/invesalius3, pull requests merged in 2024-07, with the labels that each got.

#793 Context menu improvements
  invesalius/data/slice_.py
  invesalius/gui/data_notebook.py
  invesalius/gui/dialogs.py
  invesalius/gui/task_navigator.py
  invesalius/gui/task_surface.py
Labels: enhancement, neuronavigation, ui/ux

#798 UPD: Update conda and pip packages for Python 3.11
  environment.yml
  optional-requirements.txt
  requirements.txt
Labels: dependencies

#786 Improved object and tracker fiducial registration UI
  invesalius/constants.py
  invesalius/gui/dialogs.py
  invesalius/gui/frame.py
  invesalius/gui/preferences.py
  invesalius/gui/task_navigator.py
  invesalius/gui/widgets/fiducial_buttons.py
  invesalius/net/pedal_connection.py
Labels: enhancement, ui/ux

#800 Minors visualization navigation
  invesalius/data/viewer_volume.py
  invesalius/data/visualization/coil_visualizer.py
  invesalius/gui/task_navigator.py
  invesalius/navigation/navigation.py
Labels: bug, neuronavigation

#815 Update "Getting Started" link to the new user manual
  invesalius/gui/frame.py
Labels: enhancement, document
