Repository invesalius/invesalius3, pull requests merged in 2024-04, with the labels that each got.

#746 Fix mri brightness contrast
  invesalius/control.py
Labels: enhancement

#742 Several changes related to robot control
  invesalius/data/coordinates.py
  invesalius/data/tracker_connection.py
  invesalius/data/viewer_volume.py
  invesalius/gui/dialogs.py
  invesalius/gui/preferences.py
  invesalius/gui/task_navigator.py
  invesalius/navigation/robot.py
Labels: enhancement, neuronavigation

#715 Fix print parantheses
  docs/devel/example_closure.py
Labels: bug, document
